### ISSUE TITLE
file system error

### ISSUE THREAD

**Issue by fingin** [FlashpointProject/FlashpointUltimateUpdater#4]
relevant log entries

2020-11-19 05:42:52 [INFO] *** Task End: Downloading new data... ***
2020-11-19 06:09:25 [INFO] Starting update from 8.2 to 8.2
2020-11-19 06:09:26 [INFO] *** Task Start: Fetching index 8.2 ***
2020-11-19 06:10:39 [INFO] *** Task End: Fetching index 8.2 ***
2020-11-19 06:10:39 [INFO] *** Task Start: Fetching index 8.2 ***
2020-11-19 06:11:44 [INFO] Temp folder exists. We are resuming.
2020-11-19 06:11:44 [INFO] *** Task End: Fetching index 8.2 ***
2020-11-19 06:11:44 [INFO] *** Task Start: Preparing contents... ***
2020-11-19 08:12:38 [WARNING] File from current index not found. Queued for download: Server\htdocs\ftp.untergrund.net\users\ized\prods\nano.zip\windows\nano_1024x768.exe (30c5df707e60c40f049ff9bcd7828415970b4e20)
2020-11-19 08:12:38 [WARNING] File from current index not found. Queued for download: Server\htdocs\ftp.untergrund.net\users\ized\prods\nano.zip\windows\nano_1280x720.exe (710915337ad838c67a40a8edbf63a85414740d62)
2020-11-19 08:14:59 [WARNING] File from current index not found. Queued for download: Server\htdocs\www.aggamare.com\g\mmxn\mmxn_thegameHQ_IntroWorkingOriginal_pray.swf (712ccdd8f34f0f378c8614054a9a51fffe21b682)
2020-11-19 08:14:59 [WARNING] File from current index not found. Queued for download: Server\htdocs\www.aggamare.com\g\mmxn\mmxn_thegameHQ_WorkingOriginal_pray.swf (86f8422745a9f826ca4317fdd776f9d73a076b6d)
2020-11-19 08:14:59 [WARNING] File from current index not found. Queued for download: Server\htdocs\www.aggamare.com\g\rn\rollnext_thegame100301.swf (bee0d3f06ff91ef4fe74f8c7a2bcf2f194b4445b)
2020-11-19 08:15:21 [WARNING] File from current index not found. Queued for download: Server\htdocs\www.flashgamesnexus.com\gamefiles\spongebobhalloweentruck\spongebobhalloweentruck.swf (355f1deb53fba2e0555a5fcac6310d2bff406884)
2020-11-19 08:17:35 [INFO] *** Task End: Preparing contents... ***
2020-11-19 08:17:35 [INFO] *** Task Start: Downloading new data... ***
2020-11-19 08:17:45 [INFO] Backing off download_file(...) for 0.8s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:17:45 [INFO] Backing off download_file(...) for 0.2s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:17:45 [INFO] Backing off download_file(...) for 0.5s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:17:45 [INFO] Backing off download_file(...) for 0.4s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:17:45 [INFO] Backing off download_file(...) for 0.9s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:17:45 [INFO] Backing off download_file(...) for 0.8s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:17:55 [INFO] Backing off download_file(...) for 1.4s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:17:56 [INFO] Backing off download_file(...) for 1.2s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:17:56 [INFO] Backing off download_file(...) for 0.0s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:17:56 [INFO] Backing off download_file(...) for 0.2s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:17:56 [INFO] Backing off download_file(...) for 0.8s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:17:56 [INFO] Backing off download_file(...) for 0.0s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:18:06 [INFO] Backing off download_file(...) for 2.0s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:18:07 [INFO] Backing off download_file(...) for 3.2s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:18:07 [INFO] Backing off download_file(...) for 1.7s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:18:07 [INFO] Backing off download_file(...) for 1.7s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:18:07 [INFO] Backing off download_file(...) for 1.1s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:18:07 [INFO] Backing off download_file(...) for 3.4s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:18:18 [INFO] Backing off download_file(...) for 1.9s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:18:19 [INFO] Backing off download_file(...) for 0.8s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:18:19 [INFO] Backing off download_file(...) for 0.1s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:18:19 [INFO] Backing off download_file(...) for 0.9s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:18:20 [INFO] Backing off download_file(...) for 7.9s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:18:21 [INFO] Backing off download_file(...) for 4.7s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:18:29 [INFO] Backing off download_file(...) for 2.1s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:18:30 [INFO] Backing off download_file(...) for 4.3s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:18:30 [INFO] Backing off download_file(...) for 12.9s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:18:31 [INFO] Backing off download_file(...) for 0.4s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:18:36 [INFO] Backing off download_file(...) for 11.0s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:18:38 [INFO] Backing off download_file(...) for 15.3s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:18:41 [INFO] Backing off download_file(...) for 14.4s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:18:41 [INFO] Backing off download_file(...) for 16.2s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:18:44 [INFO] Backing off download_file(...) for 8.8s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='unstable.life', port=443): Read timed out. (read timeout=10))
2020-11-19 08:20:34 [INFO] *** Task End: Downloading new data... ***
2020-11-19 08:20:34 [INFO] *** Task Start: Removing obsolete files... ***
2020-11-19 08:35:22 [INFO] *** Task End: Removing obsolete files... ***
2020-11-19 08:35:22 [INFO] *** Task Start: Creating file structure... ***
2020-11-19 12:48:03 [CRITICAL] Update failed
Traceback (most recent call last):
  File "update_gui.py", line 33, in run
  File "update.py", line 99, in perform_update
FileNotFoundError: [WinError 2] The system cannot find the file specified: '\\\\?\\D:\\flashpoint (ult)\\.tmp\\30c5df707e60c40f049ff9bcd7828415970b4e20' -> '\\\\?\\D:\\flashpoint (ult)\\Server\\htdocs\\ftp.untergrund.net\\users\\ized\\prods\\nano.zip\\windows\\nano_1024x768.exe'
2020-11-19 12:48:03 [INFO] *** Task End: Creating file structure... ***
2020-11-20 06:54:36 [INFO] Starting update from 8.2 to 8.2
2020-11-20 06:54:36 [INFO] *** Task Start: Fetching index 8.2 ***
2020-11-20 06:55:50 [INFO] *** Task End: Fetching index 8.2 ***
2020-11-20 06:55:50 [INFO] *** Task Start: Fetching index 8.2 ***
2020-11-20 06:56:55 [INFO] Temp folder exists. We are resuming.
2020-11-20 06:56:55 [INFO] *** Task End: Fetching index 8.2 ***
2020-11-20 06:56:55 [INFO] *** Task Start: Preparing contents... ***
2020-11-20 10:00:12 [WARNING] File from current index not found. Queued for download: Server\htdocs\ftp.untergrund.net\users\ized\prods\nano.zip\windows\nano_1024x768.exe (30c5df707e60c40f049ff9bcd7828415970b4e20)
2020-11-20 10:00:12 [WARNING] File from current index not found. Queued for download: Server\htdocs\ftp.untergrund.net\users\ized\prods\nano.zip\windows\nano_1280x720.exe (710915337ad838c67a40a8edbf63a85414740d62)
2020-11-20 10:03:31 [WARNING] File from current index not found. Queued for download: Server\htdocs\www.aggamare.com\g\mmxn\mmxn_thegameHQ_IntroWorkingOriginal_pray.swf (712ccdd8f34f0f378c8614054a9a51fffe21b682)
2020-11-20 10:03:31 [WARNING] File from current index not found. Queued for download: Server\htdocs\www.aggamare.com\g\mmxn\mmxn_thegameHQ_WorkingOriginal_pray.swf (86f8422745a9f826ca4317fdd776f9d73a076b6d)
2020-11-20 10:03:31 [WARNING] File from current index not found. Queued for download: Server\htdocs\www.aggamare.com\g\rn\rollnext_thegame100301.swf (bee0d3f06ff91ef4fe74f8c7a2bcf2f194b4445b)
2020-11-20 10:03:52 [WARNING] File from current index not found. Queued for download: Server\htdocs\www.flashgamesnexus.com\gamefiles\spongebobhalloweentruck\spongebobhalloweentruck.swf (355f1deb53fba2e0555a5fcac6310d2bff406884)
2020-11-20 10:05:54 [INFO] *** Task End: Preparing contents... ***
2020-11-20 10:05:54 [INFO] *** Task Start: Downloading new data... ***
2020-11-20 10:07:56 [INFO] *** Task End: Downloading new data... ***
2020-11-20 10:07:56 [INFO] *** Task Start: Removing obsolete files... ***
2020-11-20 10:26:33 [INFO] *** Task End: Removing obsolete files... ***
2020-11-20 10:26:33 [INFO] *** Task Start: Creating file structure... ***
2020-11-20 14:48:19 [CRITICAL] Update failed
Traceback (most recent call last):
  File "update_gui.py", line 33, in run
  File "update.py", line 99, in perform_update
FileNotFoundError: [WinError 2] The system cannot find the file specified: '\\\\?\\D:\\flashpointer\\.tmp\\30c5df707e60c40f049ff9bcd7828415970b4e20' -> '\\\\?\\D:\\flashpointer\\Server\\htdocs\\ftp.untergrund.net\\users\\ized\\prods\\nano.zip\\windows\\nano_1024x768.exe'
2020-11-20 14:48:19 [INFO] *** Task End: Creating file structure... ***

**Comment by fingin** [comment]
seems to be solved by excluding directories in windows defender on a pass of previous issues it seems this is irrelevant. recommended changes is a try catch and just wait 5 - 10 seconds for defender to do its thing.
